# Generated by Django 2.1.10 on 2021-07-06 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=26)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.User')),
            ],
            options={
                'db_table': 'bookinfo',
            },
        ),
    ]
