# Generated by Django 2.1.10 on 2021-07-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论量'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='发布日期'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
